const $ = (id) => document.getElementById(id);
const canvas = $("paintCanvas"),
  ctx = canvas.getContext("2d", { willReadFrequently: true }),
  shell = $("canvasShell"),
  canvasWrapper = $("canvasWrapper"),
  workspace = $("workspace"),
  workspaceStage = $("workspaceStage"),
  selectionBox = $("selectionBox"),
  toast = $("toast"),
  textContextBar = $("textContextBar"),
  darkModeToggle = $("darkModeToggle");
const colorPicker = $("colorPicker"),
  secondaryColor = $("secondaryColor"),
  brushSize = $("brushSize"),
  brushSizeValue = $("brushSizeValue"),
  saveBtn = $("saveBtn"),
  saveAsBtn = $("saveAsBtn"),
  resizeApplyBtn = $("resizeApplyBtn"),
  resizeModePercent = $("resizeModePercent"),
  resizeModePixels = $("resizeModePixels"),
  widthInput = $("widthInput"),
  heightInput = $("heightInput"),
  resizeUnitH = $("resizeUnitH"),
  resizeUnitV = $("resizeUnitV"),
  keepRatioLink = $("keepRatioLink"),
  resizeDialog = $("resizeDialog"),
  resizeOpenBtn = $("resizeOpenBtn"),
  keepResizeRatio = $("keepResizeRatio"),
  resizeCancelBtn = $("resizeCancelBtn"),
  resizeDialogClose = $("resizeDialogClose"),
  resizeDialogBackdrop = $("resizeDialogBackdrop"),
  aboutDialog = $("aboutDialog"),
  aboutDialogBackdrop = $("aboutDialogBackdrop"),
  aboutOkBtn = $("aboutOkBtn"),
  aboutVersion = $("aboutVersion"),
  skewHorizontalInput = $("skewHorizontalInput"),
  skewVerticalInput = $("skewVerticalInput"),
  sizeInfo = $("sizeInfo"),
  toolInfo = $("toolInfo"),
  posInfo = $("posInfo"),
  fileInfo = $("fileInfo"),
  formatInfo = $("formatInfo"),
  openImageBtn = $("openImageBtn"),
  zoomSlider = $("zoomSlider"),
  zoomInfo = $("zoomInfo"),
  zoomInBtn = $("zoomInBtn"),
  zoomOutBtn = $("zoomOutBtn"),
  zoomResetBtn = $("zoomResetBtn"),
  fillShape = $("fillShape"),
  fontBold = $("fontBold"),
  fontItalic = $("fontItalic"),
  fontUnderline = $("fontUnderline"),
  fontStrikethrough = $("fontStrikethrough"),
  fontAlignLeft = $("fontAlignLeft"),
  fontAlignCenter = $("fontAlignCenter"),
  fontAlignRight = $("fontAlignRight"),
  fontBackgroundFill = $("fontBackgroundFill"),
  fontFamily = $("fontFamily"),
  fontSize = $("fontSize"),
  undoBtn = $("undoBtn"),
  redoBtn = $("redoBtn"),
  copyBtn = $("copyBtn"),
  pasteBtn = $("pasteBtn"),
  swatches = $("swatches");
let drawing = false,
  startX = 0,
  startY = 0,
  lastX = 0,
  lastY = 0,
  tool = "select",
  fnZoomDown = false,
  resizing = false,
  startMouseX = 0,
  startMouseY = 0,
  startWidth = 0,
  startHeight = 0,
  zoom = 1,
  resizeMode = "percent",
  snapshot = null,
  selection = null,
  clipboardCanvas = null,
  pasteLayer = null,
  textLayer = null,
  currentFileName = "Untitled.png",
  currentMimeType = "image/png",
  currentExtension = "png",
  currentFilePath = null,
  toastTimer = null,
  undoStack = [],
  redoStack = [],
  pasteResize = null,
  selectionResize = null,
  canvasResizeState = null,
  canvasResizeRaf = 0,
  canvasResizeEvent = null,
  canvasScaleSource = null,
  selectionScaleSource = null;
const palette = [
  "#000000",
  "#ffffff",
  "#64748b",
  "#991b1b",
  "#dc2626",
  "#ef4444",
  "#f97316",
  "#facc15",
  "#22c55e",
  "#0ea5e9",
  "#2563eb",
  "#7c3aed",
  "#9ca3af",
  "#d1d5db",
  "#b45309",
  "#f9a8d4",
  "#fbbf24",
  "#fde68a",
  "#a3e635",
  "#bae6fd",
  "#60a5fa",
  "#c4b5fd",
];
const toolNames = {
  brush: "pencil",
  eraser: "eraser",
  picker: "picker",
  fill: "fill",
  select: "select",
  line: "line",
  curve: "curve",
  ellipse: "oval",
  rect: "rectangle",
  roundrect: "rounded rectangle",
  triangle: "triangle",
  righttri: "right triangle",
  diamond: "diamond",
  pentagon: "pentagon",
  hexagon: "hexagon",
  star: "star",
  arrow: "arrow",
  text: "text",
};

function isFontBold() {
  return fontBold?.classList.contains("active");
}

function isFontItalic() {
  return fontItalic?.classList.contains("active");
}

function isFontUnderline() {
  return fontUnderline?.classList.contains("active");
}

function isFontStrikethrough() {
  return fontStrikethrough?.classList.contains("active");
}

function isKeepRatioLinked() {
  return keepRatioLink?.classList.contains("active");
}
